version: "3.5"

services:
  monitor-encore-dev:
    container_name: ${PROJECT_NAME}-encore-dev
    image: node:16-alpine
    ports:
      - "8090:8090"
    volumes:
      # punto de entrada de la app symfony
      - ./:/appdata/www
    working_dir: /appdata/www
    command: [ "yarn", "dev-server" ]
    depends_on:
      - monitor-web
    networks:
      - monitor-network

  monitor-web:
    container_name: ${PROJECT_NAME}-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - "250:80"
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - monitor-be
    networks:
      - monitor-network

  monitor-be:
    env_file:
      - ./docker/php/server.env
    container_name: ${PROJECT_NAME}-be
    build:
      context: docker/php
      args:
        UID: $U_ID
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
    environment:
      PHP_INI_DIR: /usr/local/etc/php
      ###> XDEBUG 3 ###
      # Use your client IP here
      # Linux: run "ip a | grep docker0"
      # Windows (with WSL2) and Mac: host.docker.internal
      # Las configuraciones se reflejan el archivo docker/php/xdebug.ini
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9005
      XDEBUG_ID_KEY: PHPSTORM
      PHP_IDE_CONFIG: serverName=Docker
      DEBUG: 1
    working_dir: /appdata/www
    volumes:
      - ./:/appdata/www
      - ./docker/php/php.ini:$PHP_INI_DIR/php.ini
      - ./docker/php/xdebug.ini:$PHP_INI_DIR/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - monitor-db
    networks:
      - monitor-network

  monitor-db:
    container_name: ${PROJECT_NAME}-db
    hostname: monitor-db
    build:
      context: ./docker/database
    ports:
      - "36000:3306"
    environment:
      MYSQL_DATABASE: mprod_${PROJECT_NAME}
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - monitor-db-data:/var/lib/mysql
      - "./docker/database/mysqld.cnf:/etc/mysql/mysqld.cnf"
    networks:
      - monitor-network

  monitor-phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${PROJECT_NAME}-db
    depends_on:
      - monitor-db
    networks:
      - monitor-network

volumes:
  monitor-db-data:

networks:
  monitor-network:
    external: true
